language: node_js

php:
  - 5.4
  - 5.5

before_script:
 - 'npm install -g grunt-cli'
 - 'npm install'
 - wget http://cs.sensiolabs.org/get/php-cs-fixer.phar

script:
 - phpunit --coverage-text
 - output=$(php php-cs-fixer.phar fix -v --dry-run --level=psr2 .); if [[ $output ]]; then while read -r line; do echo -e "\e[00;31m$line\e[00m"; done <<< "$output"; false; fi;

notifications:
  email: false

  language: node_js
  node_js:
    - "0.8"
  before_install: npm install -g grunt-cli
  install: npm install
  before_script: grunt build